### ISSUE TITLE
[doc] toml config make an error.

### ISSUE THREAD

**Issue by WanderHuang** [yewstack/docs#36]
```toml
[package]
name = "yew-app"
version = "0.1.0"
authors = ["Yew App Developer <name@example.com>"]
edition = "2018"

[dependencies]
yew = { version = "0.13.0", features = "std_web" }
```

`yew = { version = "0.13.0", features = "std_web" }` should be replace as `yew = { version = "0.13.0", features = ["std_web"] }`.

if use `features = "std_web"`, I got error below in linux(deepin):

```txt
Caused by:
  invalid type: string "std_web", expected a sequence for key `dependencies.yew.features`
```

**this will work instead**

```toml
[package]
name = "yew-app"
version = "0.1.0"
authors = ["Yew App Developer <name@example.com>"]
edition = "2018"

[dependencies]
yew = { version = "0.13.0", features = ["std_web"] }
```
